site_name: 'Проект'
docs_dir: '../docs/ru'                           # Where to find the English markdown files
site_dir: '../build/ru'                      # Where to put the English HTML files

theme:
    name: readthedocs
#    custom_dir: '../../overrides/'                  # This is where the customization of the theme lives
#    logo: assets/images/logo.svg                    # The logo is shared by all languages
#    favicon: assets/images/favicon.ico              # The favicon is shared by all languages
    language: ru                                     # The build's language

extra:                                              # Language Selection
  alternate:  
      # Switch to English
    - name: English
      link: /en/
      lang: en

    # Switch to Russian
    - name: Русский
      link: /ru/
      lang: ru

plugins:
  - search:                                         
      lang: ru                                      # Set language for search

nav:
- "Добро пожаловать": index.md